<?php
/**
 * Copyright © Shopigo. All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product AJAX filter block
 *
 * @var $block \Shopigo\CatalogAjaxFilter\Block\ProductList\AjaxFilter
 */
// use Shopigo\CatalogAjaxFilter\Block\ProductList\AjaxFilter;
?>
<script type="text/x-magento-init">
    {
        ".block.filter": {
            "productListCatalogAjaxFilter": {
                "ajaxRequestTimeout": <?= /* @escapeNotVerified */ $block->getAjaxRequestTimeout() ?>,
                "scrollToTopEnabled": <?= /* @escapeNotVerified */ $block->getIsScrollToTopEnabled() ?>,
                "scrollToTopEasing": "<?= $block->getScrollToTopEasing() ?>",
                "scrollToTopDuration": <?= /* @escapeNotVerified */ $block->getScrollToTopDuration() ?>,
                "scrollToTopOffset": <?= /* @escapeNotVerified */ $block->getScrollToTopOffset() ?>
            }
        }
    }
</script>
